server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
    datasource:
      url: jdbc:h2:mem:db_test
      username: tester
      password: password
      driver-class-name: org.h2.Driver
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: ${POSTGRES_URL}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        security: error
